---
title: "SpatialLIBD exploration"
output:
  html_document:
    df_print: paged
---

### 1. Install SpatialLIBD

```{r, eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install("DropletUtils")
BiocManager::install("spatialLIBD")

## Check that you have a valid Bioconductor installation
BiocManager::valid()
```

### Downloading the data with spatialLIBD
`spe` is the SpatialExperiment object with all the spot-level data and the histology information for visualization of the data.

`sce_layer` is the SingleCellExperiment object with the layer-level data.

`modeling_results` contains the layer-level enrichment, pairwise and anova statistics.

```{r, eval = FALSE}
library("spatialLIBD")
library("DropletUtils")

## Connect to ExperimentHub
ehub <- ExperimentHub::ExperimentHub()
spe <- fetch_data(type = "spe", eh = ehub)
```

```{r, eval = FALSE}
## Connect to ExperimentHub
setwd('..')
colDF <- data.frame(spe@colData@listData)
countMatrix <- spe@assays@data@listData[["counts"]]
sampleIds <- spe@int_metadata[["imgData"]]@listData[["sample_id"]]
spatial_coords <- spe@int_colData@listData[["spatialCoords"]]
for (idx in seq(length(sampleIds))){
  sampleId <- sampleIds[idx]
  dirToSave <- file.path(getwd(), "data", paste0("Spatial_LIBD_", sampleId))
  rows <- which(colDF$sample_id == sampleId)
  coords <- data.frame(spatial_coords[rows, ])
  write.csv(coords,file.path(dirToSave, "spatial_coords.csv"), row.names = FALSE)
  
  #subMatrix <- countMatrix[, rows] # sparse count matrix for sample
  #write10xCounts(dirToSave, subMatrix, type ="sparse", genome = "hg19")
  #df <- colDF[rows, ]
  #write.csv(df,file.path(dirToSave, "spot_info.csv"), row.names = FALSE)
  #download.file(spe@int_metadata[["imgData"]]@listData[["data"]][[idx]]@url,file.path(dirToSave, paste0(sampleId, "_tissue_lowres_image.png")), mode = 'wb')
}
```

